/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unhcr.eg.registration.tool.token.printing.panel;

import java.text.SimpleDateFormat;
import org.unhcr.eg.registration.tool.token.printing.models.TokenDetails;

/**
 *
 * @author UNHCRuser
 */
public class RequestDetailsPanel extends javax.swing.JPanel {

    private TokenDetails details;
    private final SimpleDateFormat sdf = new SimpleDateFormat(
            "EEE, d MMM yyyy HH:mm:ss");

    /**
     * Creates new form ComplainToken
     */
    public RequestDetailsPanel(TokenDetails details) {
        this.details = details;
        initComponents();
        updatePanel(details);
    }

    public void updatePanel(TokenDetails details) {
        arrivalDateAndTimeLabel.setText(sdf.format(details.getAccesDateTime()));
        caseNumberLabel_1.setText(details.getCaseNumber());
        familySizeLabel_1.setText(Integer.toString(details.getFamilySize()));
        tokenNumberLabel_1.setText(Integer.toString(details.getTokenNumber()));
        visitNumberLabel_1.setText(Integer.toString(details.getVisitNumber()));
        locationLabel_1.setText(details.getLocation());
        gateLabel_1.setText(details.getGateName());
        visitReasonLabel_1.setText(details.getReasonForVisit());
    }

    public TokenDetails getDetails() {
        return details;
    }

    public void setDetails(TokenDetails details) {
        this.details = details;
        updatePanel(details);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        arrivalPanel = new javax.swing.JPanel();
        ArrivalDateAndTimeLabel_ = new javax.swing.JLabel();
        arrivalDateAndTimeLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        TokenPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TokenNumberLabel_ = new javax.swing.JLabel();
        tokenNumberLabel_1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        visitNumberLabel_1 = new javax.swing.JLabel();
        casePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        caseNumberLabel_1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        familySizeLabel_1 = new javax.swing.JLabel();
        visitPanel = new javax.swing.JPanel();
        locationLabel_ = new javax.swing.JLabel();
        locationLabel_1 = new javax.swing.JLabel();
        gateLabel_ = new javax.swing.JLabel();
        gateLabel_1 = new javax.swing.JLabel();
        visitReasonLabel_ = new javax.swing.JLabel();
        visitReasonLabel_1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        arrivalPanel.setLayout(new java.awt.BorderLayout());

        ArrivalDateAndTimeLabel_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(ArrivalDateAndTimeLabel_, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.ArrivalDateAndTimeLabel_.text")); // NOI18N
        arrivalPanel.add(ArrivalDateAndTimeLabel_, java.awt.BorderLayout.NORTH);

        arrivalDateAndTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        arrivalDateAndTimeLabel.setForeground(new java.awt.Color(0, 102, 204));
        arrivalDateAndTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(arrivalDateAndTimeLabel, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.arrivalDateAndTimeLabel.text")); // NOI18N
        arrivalPanel.add(arrivalDateAndTimeLabel, java.awt.BorderLayout.CENTER);

        add(arrivalPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setLayout(new java.awt.BorderLayout());

        TokenPanel.setBackground(new java.awt.Color(255, 255, 255));
        TokenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.TokenPanel.border.title"))); // NOI18N
        TokenPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        TokenNumberLabel_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(TokenNumberLabel_, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.TokenNumberLabel_.text")); // NOI18N
        jPanel1.add(TokenNumberLabel_, java.awt.BorderLayout.NORTH);

        tokenNumberLabel_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        tokenNumberLabel_1.setForeground(new java.awt.Color(0, 102, 204));
        tokenNumberLabel_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tokenNumberLabel_1.setLabelFor(TokenNumberLabel_);
        org.openide.awt.Mnemonics.setLocalizedText(tokenNumberLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.tokenNumberLabel_1.text")); // NOI18N
        jPanel1.add(tokenNumberLabel_1, java.awt.BorderLayout.CENTER);

        TokenPanel.add(jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.jLabel2.text")); // NOI18N
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        visitNumberLabel_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        visitNumberLabel_1.setForeground(new java.awt.Color(0, 102, 204));
        visitNumberLabel_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(visitNumberLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.visitNumberLabel_1.text")); // NOI18N
        jPanel6.add(visitNumberLabel_1, java.awt.BorderLayout.CENTER);

        TokenPanel.add(jPanel6);

        centerPanel.add(TokenPanel, java.awt.BorderLayout.CENTER);

        casePanel.setBackground(new java.awt.Color(255, 255, 255));
        casePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.casePanel.border.title"))); // NOI18N
        casePanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.jLabel5.text")); // NOI18N
        casePanel.add(jLabel5);

        caseNumberLabel_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        caseNumberLabel_1.setForeground(new java.awt.Color(0, 102, 204));
        org.openide.awt.Mnemonics.setLocalizedText(caseNumberLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.caseNumberLabel_1.text")); // NOI18N
        casePanel.add(caseNumberLabel_1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.jLabel7.text")); // NOI18N
        casePanel.add(jLabel7);

        familySizeLabel_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        familySizeLabel_1.setForeground(new java.awt.Color(0, 102, 204));
        org.openide.awt.Mnemonics.setLocalizedText(familySizeLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.familySizeLabel_1.text")); // NOI18N
        casePanel.add(familySizeLabel_1);

        centerPanel.add(casePanel, java.awt.BorderLayout.PAGE_START);

        visitPanel.setLayout(new java.awt.GridBagLayout());

        locationLabel_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(locationLabel_, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.locationLabel_.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        visitPanel.add(locationLabel_, gridBagConstraints);

        locationLabel_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(locationLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.locationLabel_1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        visitPanel.add(locationLabel_1, gridBagConstraints);

        gateLabel_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(gateLabel_, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.gateLabel_.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        visitPanel.add(gateLabel_, gridBagConstraints);

        gateLabel_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(gateLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.gateLabel_1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        visitPanel.add(gateLabel_1, gridBagConstraints);

        visitReasonLabel_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(visitReasonLabel_, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.visitReasonLabel_.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        visitPanel.add(visitReasonLabel_, gridBagConstraints);

        visitReasonLabel_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(visitReasonLabel_1, org.openide.util.NbBundle.getMessage(RequestDetailsPanel.class, "RequestDetailsPanel.visitReasonLabel_1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        visitPanel.add(visitReasonLabel_1, gridBagConstraints);

        centerPanel.add(visitPanel, java.awt.BorderLayout.SOUTH);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArrivalDateAndTimeLabel_;
    private javax.swing.JLabel TokenNumberLabel_;
    private javax.swing.JPanel TokenPanel;
    private javax.swing.JLabel arrivalDateAndTimeLabel;
    private javax.swing.JPanel arrivalPanel;
    private javax.swing.JLabel caseNumberLabel_1;
    private javax.swing.JPanel casePanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel familySizeLabel_1;
    private javax.swing.JLabel gateLabel_;
    private javax.swing.JLabel gateLabel_1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel locationLabel_;
    private javax.swing.JLabel locationLabel_1;
    private javax.swing.JLabel tokenNumberLabel_1;
    private javax.swing.JLabel visitNumberLabel_1;
    private javax.swing.JPanel visitPanel;
    private javax.swing.JLabel visitReasonLabel_;
    private javax.swing.JLabel visitReasonLabel_1;
    // End of variables declaration//GEN-END:variables
}
