/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unhcr.eg.registration.tool.dataQuality;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.Children;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.unhcr.eg.registration.tool.dataQuality.node.RootDataQualityNode;
import org.unhcr.eg.registration.tool.dataQuality.node.factory.RootCategoryChildFactory;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.unhcr.eg.registration.tool.dataQuality//Evaluator//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EvaluatorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = true)
@ActionID(category = "Window", id = "org.unhcr.eg.registration.tool.dataQuality.EvaluatorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EvaluatorAction",
        preferredID = "EvaluatorTopComponent"
)
@Messages({
    "CTL_EvaluatorAction=Quality Framework",
    "CTL_EvaluatorTopComponent=Quality Framework Window",
    "HINT_EvaluatorTopComponent=This is a Evaluator window"
})
public final class EvaluatorTopComponent extends TopComponent implements ExplorerManager.Provider {

    private transient ExplorerManager em = new ExplorerManager();
    private OutlineView view = new OutlineView();

    public EvaluatorTopComponent() {
        initComponents();
        setName(Bundle.CTL_EvaluatorTopComponent());
        setToolTipText(Bundle.HINT_EvaluatorTopComponent());
        em.setRootContext(new RootDataQualityNode(Children.create(new RootCategoryChildFactory(), true)));
        em.getRootContext().setDisplayName("Quality Framework");
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        add(view, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }
}
