/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unhcr.eg.registration.tool.token.printing;

import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import org.jdesktop.swingx.painter.GlossPainter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.unhcr.eg.registration.security.action.LongTaskBackgroundAction;
import org.unhcr.eg.registration.security.em.EntityManagerSingleton;
import org.unhcr.eg.registration.security.exchange.ExcelSaver;
import org.unhcr.eg.registration.tool.token.printing.service.TokenManagerService;
import org.unhcr.eg.registration.tool.token.printing.service.TokenSummaryTableModel;
import org.unhcr.eg.registration.tool.token.printing.service.TokenTableModel;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.unhcr.eg.registration.tool.token.printing//TokenReport//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TokenReportTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.unhcr.eg.registration.tool.token.printing.TokenReportTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TokenReportAction",
        preferredID = "TokenReportTopComponent"
)
@Messages({
    "CTL_TokenReportAction=TokenReport",
    "CTL_TokenReportTopComponent=TokenReport Window",
    "HINT_TokenReportTopComponent=This is a TokenReport window"
})
public final class TokenReportTopComponent extends TopComponent {

    private final TokenTableModel tokenTableModel;
    private final TokenSummaryTableModel tokenSummaryTableModel;

    public TokenReportTopComponent() {
        initComponents();
        setName(Bundle.CTL_TokenReportTopComponent());
        setToolTipText(Bundle.HINT_TokenReportTopComponent());
        tokenTableModel = new TokenTableModel();
        tokenSummaryTableModel = new TokenSummaryTableModel();
        tokenTable.addHighlighter(HighlighterFactory.createAlternateStriping(new Color(234, 234, 234), Color.WHITE));
        tokenTable.setModel(tokenTableModel);

        summaryXTable.addHighlighter(HighlighterFactory.createAlternateStriping(new Color(234, 234, 234), Color.WHITE));
        summaryXTable.setModel(tokenSummaryTableModel);

        childHeader.setBackground(new Color(192, 192, 192, 100));
        child2Header.setBackground(new Color(192, 192, 192, 100));

        childHeader.setBackgroundPainter(new GlossPainter(GlossPainter.GlossPosition.TOP));
        child2Header.setBackgroundPainter(new GlossPainter(GlossPainter.GlossPosition.TOP));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        childHeader = new org.jdesktop.swingx.JXHeader();
        jToolBar1 = new javax.swing.JToolBar();
        loadButton = new javax.swing.JButton();
        todayButton = new javax.swing.JButton();
        exportToExcelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        cancelButton = new javax.swing.JButton();
        printAgainButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokenTable = new org.jdesktop.swingx.JXTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        child2Header = new org.jdesktop.swingx.JXHeader();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        summaryXTable = new org.jdesktop.swingx.JXTable();

        setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setLastDividerLocation(700);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        childHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1417627941_699325-icon-53-notebook-list-32.png"))); // NOI18N
        childHeader.setTitle(org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.childHeader.title")); // NOI18N
        childHeader.setTitleFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel7.add(childHeader, java.awt.BorderLayout.NORTH);

        jToolBar1.setRollover(true);

        loadButton.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        loadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415040031_698860-icon-129-cloud-download-16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(loadButton, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.loadButton.text")); // NOI18N
        loadButton.setFocusable(false);
        loadButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loadButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loadButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(loadButton);

        todayButton.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        todayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415039476_today.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(todayButton, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.todayButton.text")); // NOI18N
        todayButton.setFocusable(false);
        todayButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        todayButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        todayButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        todayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(todayButton);

        exportToExcelButton.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        exportToExcelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415295482_receipt-excel-text.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exportToExcelButton, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.exportToExcelButton.text")); // NOI18N
        exportToExcelButton.setFocusable(false);
        exportToExcelButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exportToExcelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        exportToExcelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exportToExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportToExcelButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(exportToExcelButton);
        jToolBar1.add(jSeparator1);

        cancelButton.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415037030_698591-icon-79-document-cancel-16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.cancelButton.text")); // NOI18N
        cancelButton.setFocusable(false);
        cancelButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cancelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cancelButton);

        printAgainButton.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        printAgainButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/printer-16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(printAgainButton, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.printAgainButton.text")); // NOI18N
        printAgainButton.setFocusable(false);
        printAgainButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printAgainButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        printAgainButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        printAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAgainButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(printAgainButton);

        previewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1421961775_Preview.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(previewButton, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.previewButton.text")); // NOI18N
        previewButton.setFocusable(false);
        previewButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        previewButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        previewButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(previewButton);

        jPanel7.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.NORTH);

        tokenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tokenTable.setColumnControlVisible(true);
        tokenTable.setHorizontalScrollEnabled(true);
        tokenTable.setShowVerticalLines(false);
        tokenTable.setVisibleRowCount(15);
        jScrollPane1.setViewportView(tokenTable);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        child2Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1417628058_table_select_all.png"))); // NOI18N
        child2Header.setTitle(org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.child2Header.title")); // NOI18N
        child2Header.setTitleFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel8.add(child2Header, java.awt.BorderLayout.NORTH);

        jToolBar2.setRollover(true);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415040031_698860-icon-129-cloud-download-16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415039476_today.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jButton3.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/registration/tool/token/printing/1415295482_receipt-excel-text.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(TokenReportTopComponent.class, "TokenReportTopComponent.jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        jPanel8.add(jToolBar2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.NORTH);

        summaryXTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        summaryXTable.setColumnControlVisible(true);
        summaryXTable.setHorizontalScrollEnabled(true);
        summaryXTable.setVisibleRowCount(5);
        jScrollPane2.setViewportView(summaryXTable);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel5);

        jPanel6.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    protected void adaptTable() {
        TableColumnModel columnModel = tokenTable.getColumnModel();
        if (columnModel.getColumnCount() > 0) {
            tokenTable.getColumn("TokenDistributedGUID").setResizable(false);
            tokenTable.getColumn("TokenDistributedGUID").setMaxWidth(0);
            tokenTable.getColumn("TokenDistributedGUID").setPreferredWidth(0);
            TableRowFilterSupport.forTable(tokenTable).searchable(true).useTableRenderers(true).apply();
        }
        columnModel = summaryXTable.getColumnModel();
        if (columnModel.getColumnCount() > 0) {
            TableRowFilterSupport.forTable(summaryXTable).searchable(true).useTableRenderers(true).apply();
        }
    }


    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        try {
            tokenTableModel.getAllToken(EntityManagerSingleton.getDefault().getConnection());
            adaptTable();
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void todayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayButtonActionPerformed
        try {
            tokenTableModel.getTodayToken(EntityManagerSingleton.getDefault().getConnection());
            adaptTable();
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_todayButtonActionPerformed

    private void exportToExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportToExcelButtonActionPerformed

        ExcelSaver excelSaver = new ExcelSaver(tokenTable, "Token_document.xls", "Tokens");
        excelSaver.saveTable();
    }//GEN-LAST:event_exportToExcelButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        NotifyDescriptor nd = new NotifyDescriptor.Confirmation("Do you want to inactivate this token?", "Inactivation confirmation", NotifyDescriptor.YES_NO_OPTION);
        Object result = DialogDisplayer.getDefault().notify(nd);
        if (result != NotifyDescriptor.OK_OPTION) {
            return;
        }
        try {
            Connection con = EntityManagerSingleton.getDefault().getConnection();
            int selectedRow = tokenTable.getSelectedRow();
            String updateSQL = "UPDATE tmp_TokenReport\n"
                    + "SET      TokenStatus = N'X'\n"
                    + "WHERE     (TokenDistributedGUID = ?)";

            HashMap<Integer, Object> map = new HashMap<>();
            String tokenGUID = (String) tokenTableModel.getValueAt(tokenTable.convertRowIndexToModel(selectedRow), 0);
            map.put(1, tokenGUID);
            tokenTableModel.executePreparedQuery(con, updateSQL, map);
            tokenTableModel.getAllToken(EntityManagerSingleton.getDefault().getConnectionForproGres());
            adaptTable();
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void printAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAgainButtonActionPerformed

        int selectedRow = tokenTable.getSelectedRow();
        final String caseNumber = (String) tokenTableModel.getValueAt(tokenTable.convertRowIndexToModel(selectedRow), 5);
        final String reason = (String) tokenTableModel.getValueAt(tokenTable.convertRowIndexToModel(selectedRow), 11);
        final String gate = (String) tokenTableModel.getValueAt(tokenTable.convertRowIndexToModel(selectedRow), 13);
        LongTaskBackgroundAction action = new LongTaskBackgroundAction("Print Token for " + caseNumber) {

            @Override
            protected void mainAction() {
                TokenManagerService.printTokenAction(reason, caseNumber, gate, TokenPrintingTopComponent.reportLocation);
            }
        };
        action.actionPerformed(evt);

    }//GEN-LAST:event_printAgainButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        int selectedRow = tokenTable.getSelectedRow();
        final String caseNumber = (String) tokenTableModel.getValueAt(tokenTable.convertRowIndexToModel(selectedRow), 5);
        final String tokenGUID = (String) tokenTableModel.getValueAt(tokenTable.convertRowIndexToModel(selectedRow), 0);
        LongTaskBackgroundAction action = new LongTaskBackgroundAction("Preview Token for " + caseNumber) {

            @Override
            protected void mainAction() {
                TokenManagerService.effectivePreviewToken(tokenGUID, caseNumber, TokenPrintingTopComponent.reportViewLocation);
            }
        };
        action.actionPerformed(evt);
    }//GEN-LAST:event_previewButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tokenSummaryTableModel.getAllToken(EntityManagerSingleton.getDefault().getConnection());
            adaptTable();
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            tokenSummaryTableModel.getTodayToken(EntityManagerSingleton.getDefault().getConnection());
            adaptTable();
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ExcelSaver excelSaver = new ExcelSaver(summaryXTable, "Token_Summary_document.xls", "Tokens Summary");
        excelSaver.saveTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private org.jdesktop.swingx.JXHeader child2Header;
    private org.jdesktop.swingx.JXHeader childHeader;
    private javax.swing.JButton exportToExcelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton previewButton;
    private javax.swing.JButton printAgainButton;
    private org.jdesktop.swingx.JXTable summaryXTable;
    private javax.swing.JButton todayButton;
    private org.jdesktop.swingx.JXTable tokenTable;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
