/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unhcr.eg.registration.security.report;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.windows.TopComponent;

/**
 *
 * @author UNHCRUser
 */
@ConvertAsProperties(dtd = "-//org.unhcr.eg.registration.security.report//ReportViewer//EN", autostore = false)
public class ReportViewer extends TopComponent {

    net.sf.jasperreports.view.JRViewer rViewer;

    /**
     * Creates new form ReportViewer
     */
    public ReportViewer() {
        initComponents();
    }

    public void setReportViewer(net.sf.jasperreports.view.JRViewer rViewer) {
        if (this.rViewer == null) {
            this.rViewer = rViewer;
            add(this.rViewer, BorderLayout.CENTER);
            this.rViewer.setFitPageZoomRatio();
        } else {
            remove(this.rViewer);
            this.rViewer = rViewer;
            add(this.rViewer, BorderLayout.CENTER);
            this.rViewer.setFitPageZoomRatio();
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    protected void componentActivated() {
        super.componentActivated();
    }

    @Override
    protected void componentDeactivated() {
        super.componentDeactivated();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER; //To change body of generated methods, choose Tools | Templates.
    }
}
