/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unhcr.eg.data.management.exchange;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.unhcr.eg.registration.security.filechooser.filter.ExcelFilter;

public final class LoadListDetailsVisualPanel1 extends JPanel {

    private File file;
    public static final String PROP_FILE = "file";

    /**
     * Get the value of file
     *
     * @return the value of file
     */
    public File getFile() {
        return file;
    }

    /**
     * Set the value of file
     *
     * @param file new value of file
     */
    public void setFile(File file) {
        File oldFile = this.file;
        
        this.file = file;
        fileSelectedTextField.setText(file.getAbsolutePath());
        fileSelectedTextField.setToolTipText(file.getAbsolutePath());
        if (file == null) {
            fileSelectedTextField.setText("");
            fileSelectedTextField.setToolTipText("");
        }
        firePropertyChange(PROP_FILE, oldFile, file);
    }
    JFileChooser fileChooser = new JFileChooser();

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JTextField getFileSelectedTextField() {
        return fileSelectedTextField;
    }

    /**
     * Creates new form LoadListDetailsVisualPanel1
     */
    public LoadListDetailsVisualPanel1() {
        fileChooser.addChoosableFileFilter(new ExcelFilter());
        fileChooser.setAcceptAllFileFilterUsed(true);
        initComponents();
    }

    @Override
    public String getName() {
        return "Select data file to import";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loaderButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fileSelectedLabel = new javax.swing.JLabel();
        fileSelectedTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        loaderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unhcr/eg/data/management/exchange/Document-Copy-icon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(loaderButton, org.openide.util.NbBundle.getMessage(LoadListDetailsVisualPanel1.class, "LoadListDetailsVisualPanel1.loaderButton.text")); // NOI18N
        loaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaderButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loaderButton, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(fileSelectedLabel, org.openide.util.NbBundle.getMessage(LoadListDetailsVisualPanel1.class, "LoadListDetailsVisualPanel1.fileSelectedLabel.text")); // NOI18N

        fileSelectedTextField.setEditable(false);
        fileSelectedTextField.setToolTipText(org.openide.util.NbBundle.getMessage(LoadListDetailsVisualPanel1.class, "LoadListDetailsVisualPanel1.fileSelectedTextField.toolTipText")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileSelectedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileSelectedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileSelectedLabel)
                    .addComponent(fileSelectedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void loaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaderButtonActionPerformed

        int returnVal = fileChooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println(fileChooser.getSelectedFile());
            setFile(fileChooser.getSelectedFile());
        } else {
        }

    }//GEN-LAST:event_loaderButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileSelectedLabel;
    private javax.swing.JTextField fileSelectedTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loaderButton;
    // End of variables declaration//GEN-END:variables
}
